version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./festibook-db/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - fbook


  #   스프링 로컬로 실행 시 주석 처리하고 DB만 도커 빌드
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgresql
    ports:
      - 8080:8080
    container_name: springboot
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - fbook

networks:
  fbook:
    driver: bridge

