spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: naver
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: env.properties
  profiles:
    active: jwt, oauth

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true

  ai:
    openai:
      chat:
        api-key: ${GPT_API_KEY}  # 환경 변수로 API 키 설정
        base-url: "https://api.openai.com/v1/chat/completions"
        options:
          model: "gpt-4o-mini"
          temperature: 0.7  # 생성된 응답의 창의성 조절
          max-tokens: 1000   # 생성할 최대 토큰 수


logging:
  level:
    org.springframework.security: TRACE

jwt:
  token:
    access-expire-length: 43200000 # 12시간
    refresh-expire-length: 604800000 # 7일

open-api:
  event-api:
    url: http://apis.data.go.kr/B551011/KorService1/searchFestival1
  event-detail-api:
    common-url: http://apis.data.go.kr/B551011/KorService1/detailCommon1
    intro-url: http://apis.data.go.kr/B551011/KorService1/detailIntro1
  service-key: ${OPEN_API_SERVICE_KEY}


springdoc:
  swagger-ui:
    path: /swagger

server:
  error:
    include-message: always # 임시로 오류 메시지 나오도록
